USE
[NESS]
GO
INSERT INTO [Account].[Account] ([User_name],
                                 [Password],
                                 [Hash],
                                 [Salt])
VALUES ('tucute123', 'Hoanganh1', '2bb12bb', 'ab$45'),
('lamthanhluan2907', 'ductrong', '768eb66', 'ih&g3'),
('vanbui.work', 'Trungquan123', '9f0e4b9', 'hs!19'),
('guangyaoaoao', 'passmon100', 'df29e22', 'fh#02'),
('congbang', 'ihatepdm', 'a00467e', 'vh*38'),
('phamvu', 'levansy1', 'b513c27', 'ai%18'),
('huynhtrankhanh', 'khanhday123!', 'b634007', 'bh^17')
GO
INSERT INTO [Account].[Patient]
VALUES (1, 'Nguyen Hoang Anh Tu', '2002-06-13', 'Male', 'nghganhtu@gmail.com'),
(3, 'Bui Thi Cam Van', '2002-12-08', 'Female', 'buicamvan.work@gmail.com'),
(4, 'Nguyen Quang Dieu', '2002-05-29', 'Male', 'guangyao@gmail.com'),
(5, 'Nguyen Luan Cong Bang', '2002-11-07', 'Male', 'congbang.1107@gmail.com'),
(7, 'Huynh Tran Khanh', '2003-01-13', 'Male', 'htk2003@gmail.com')
GO
INSERT INTO [Account].[Specialist]
VALUES (2,
        'Lam Thanh Luan',
        '1990-06-13',
        'Male',
        'lamthanhluan@gmail.com',
        '0913517039',
        '403697021687539',
        'Sai Gon University'),
(6,
 'Pham Minh Vu',
 '1985-06-13',
 'Male',
 'laimaybay@gmail.com',
 '0947513068',
 '5103697140687439',
 'International University')
GO
INSERT INTO [Booking].[HealingInformation]
VALUES (1,
        'Quan 3',
        '2023-05-01',
        '300000',
        'I will help you to get out of your mental problem within 1 hour',
        'Please come in the morning'),
(2, 'Quan 1', '2023-05-01', '400000', 'If you need help, come to me', NULL),
(1, 'Quan 3', '2023-05-03', '300000', 'I will help you to get out of your mental problem within 1 hour', NULL),
(2, 'Quan 1', '2023-05-05', '400000', 'If you need help, come to me', 'I am free in the afternoon'),
(2, 'Quan 1', '2023-05-06', '400000', 'If you need help, come to me', NULL),
(2, 'Quan 1', '2023-05-13', '400000', 'If you need help, come to me', NULL),
(1, 'Quan 3', '2023-05-13', '300000', 'I will help you to get out of your mental problem within 1 hour', NULL),
(2, 'Quan 1', '2023-05-16', '400000', 'If you need help, come to me', 'I am free in the afternoon'),
(1,
 'Quan 3',
 '2023-05-18',
 '300000',
 'I will help you to get out of your mental problem within 1 hour',
 'The meeting will be hold online'),
(2, 'Quan 1', '2023-05-20', '400000', 'If you need help, come to me', NULL)
GO
INSERT INTO [Booking].[Booking]
VALUES (5, 1),
(1, 3  ),
(2, 2  ),
(4, 1  ),
(1, 1  ),
(1, 2  ),
(5, 4  ),
(4, 1  )
GO
INSERT INTO [Disease].[Disease]
VALUES (1,
        'Depression',
        'Depression is a mood disorder that causes a persistent feeling of sadness and loss of interest.'),
(2, 'Stress', 'Stress is a consequence of experiencing pressure or tension.'),
(3,
 'Anxiety',
 'Anxiety is an emotion caused by a perceived or experienced threat, which often leads to an avoidance or evasion thereof.'),
(4,
 'Borderline',
 'Borderline is a personality disorder. People with borderline have fast-changing feelings toward friendship, love, and so on.'),
(5,
 'Migraine',
 'Migraine is an illness, where regular intense attacks of headache occur. In the case of migraine, this headache often only takes place at one side of the head, and causes a pounding type of pain'),
(6,
 'Alzheimer',
 'Alzheimer disease is a brain disorder that slowly destroys memory and thinking skills and, eventually, the ability to carry out the simplest tasks.'),
(7,
 'Burnout',
 'Burnout is a mental disorder, in which you are totally burned out. You just cannot go on and are often very emotional.'),
(8,
 'Schizophrenia',
 'Schizophrenia is a mental disorder characterized by continuous or relapsing episodes of psychosis'),
(9,
 'Post-Traumatic Stress Disorder',
 'Posttraumatic Stress Disorder (PTSD) is a psychiatric disorder that can occur in people who have experienced or witnessed a traumatic event, series of events or set of circumstances.'),
(10,
 'Bipolar Disorder',
 'Bipolar disorder is a brain disorders that causes changes in a person’s mood, energy, and ability to function.')
GO
INSERT INTO [Disease].[Symptom]
VALUES (1, 'Eating disorder', 'Physical'),
(2, 'Sleeping disorder', 'Physical'),
(3, 'Having fewer feelings', 'Mental'),
(4, 'Decrease libido', 'Physical'),
(5, 'Tension', 'Mental'),
(6, 'Irritability', 'Mental'),
(7, 'Guilty thoughts', 'Mental'),
(8, 'Delusion', 'Mental'),
(9, 'Attention losing', 'Mental'),
(10, 'Doubting the meaning of life', 'Mental'),
(11, 'Worrying', 'Mental'),
(12, 'Headaches', 'Physical'),
(13, 'Memory issue', 'Mental'),
(14, 'Indecisiveness', 'Mental'),
(15, 'Melancholy mood', 'Mental'),
(16, 'Self-deprecation', 'Mental'),
(17, 'Heart palpitations', 'Physical'),
(18, 'Experiencing gastrointestinal (GI) problems', 'Physical'),
(19, 'Weight loss', 'Physical'),
(20, 'Decrease appetite', 'Physical'),
(21, 'Quick mood shifts', 'Mental'),
(22, 'Identity disorder', 'Mental'),
(23, 'Self-harm thoughts', 'Mental'),
(24, 'Feeling nauseous', 'Physical'),
(25, 'Social isolation', 'Mental'),
(26, 'Fatigue', 'Physical'),
(27, 'Thoughts of death/suicide', 'Mental'),
(28, 'Slow movement and speechs', 'Physical'),
(29, 'Increase purposeless physical activity', 'Physical'),
(30, 'Loss of interest', 'Mental'),
(31, 'Weight Gain', 'Physical'),
(32, 'Feeling worthless', 'Mental'),
(33, 'Pain and illness', 'Physical'),
(34, 'Breathing rapidly', 'Physical'),
(35, 'Feeling restless', 'Mental'),
(36, 'Muscle ache', 'Physical'),
(37, 'Language disorder', 'Mental')
GO
INSERT INTO [Disease].[DiseaseSymptom]
VALUES (1, 1, 15),
(2, 1, 30),
(3, 1, 19),
(4, 1, 31),
(5, 1, 2),
(6, 1, 26),
(7, 1, 28),
(8, 1, 29),
(9, 1, 32),
(10, 1, 7),
(11, 1, 9),
(12, 1, 14),
(13, 1, 23),
(14, 1, 27),
(15, 2, 1),
(16, 2, 2),
(17, 2, 26),
(18, 2, 17),
(19, 2, 33),
(20, 2, 6),
(21, 2, 15),
(22, 2, 30),
(23, 2, 16),
(24, 2, 25),
(25, 2, 9),
(26, 2, 11),
(27, 2, 13),
(28, 2, 14),
(29, 3, 11),
(30, 3, 2),
(31, 3, 9),
(32, 3, 26),
(33, 3, 17),
(34, 3, 34),
(35, 3, 18),
(36, 4, 21),
(37, 4, 23),
(38, 4, 6),
(39, 4, 27),
(40, 4, 22),
(41, 4, 25),
(42, 4, 35),
(43, 5, 35),
(44, 5, 6),
(45, 5, 26),
(46, 5, 12),
(47, 5, 36),
(48, 5, 37),
(49, 5, 24),
(50, 5, 13),
(51, 6, 13),
(52, 6, 14),
(53, 6, 21),
(54, 6, 37),
(55, 7, 2),
(56, 7, 33),
(57, 7, 20),
(58, 7, 17),
(59, 7, 26),
(60, 8, 8),
(61, 8, 3),
(62, 8, 37),
(63, 8, 4),
(64, 8, 25),
(65, 8, 9),
(66, 8, 13),
(67, 8, 27),
(68, 8, 6),
(69, 9, 2),
(70, 9, 9),
(71, 9, 15),
(72, 9, 10),
(73, 9, 5),
(74, 9, 13),
(75, 9, 30),
(76, 9, 6),
(77, 9, 23),
(78, 10, 2),
(79, 10, 27),
(80, 10, 9),
(81, 10, 35),
(82, 10, 28),
(83, 10, 20),
(84, 10, 7),
(85, 10, 26),
(86, 10, 32),
(87, 10, 30)
GO
INSERT INTO [Test].[Test]
VALUES (1, 27, 9, 1),
(2, 40, 10, 2),
(3, 40, 10, 3),
(4, 17, 9, 4),
(5, NULL, NULL, 5),
(6, NULL, NULL, 6),
(7, NULL, NULL, 7),
(8, 40, 10, 8),
(9, 18, 18, 9),
(10, 48, 12, 10)
GO
INSERT INTO [Test].[Result]
VALUES (1, 1, 80, NULL),
(2, 1, 100, NULL),
(3, 2, 80, NULL),
(4, 2, 100, NULL),
(5, 3, 80, NULL),
(6, 3, 100, NULL),
(7, 4, 80, NULL),
(8, 4, 100, NULL),
(9, 5, 80, NULL),
(10, 5, 100, NULL),
(11, 6, 80, NULL),
(12, 6, 100, NULL),
(13, 7, 80, NULL),
(14, 7, 100, NULL),
(15, 8, 80, NULL),
(16, 8, 100, NULL),
(17, 9, 80, NULL),
(18, 9, 100, NULL),
(19, 10, 80, NULL),
(20, 10, 100, NULL)
GO
INSERT INTO [Account].[PatientRecord]
VALUES (1, 1, 2),
(2, 5, 19),
(3, 1, 4),
(4, 3, 15),
(5, 4, 1),
(6, 1, 20),
(7, 1, 17),
(8, 5, 2),
(9, 5, 3),
(10, 3, 16),
(11, 4, 8)
GO
INSERT INTO [Test].[Answer]
VALUES (1, 'Not at all', 0),
(2, 'Several days', 1),
(3, 'More than half the days', 2),
(4, 'Nearly every day', 3),
(5, 'Never', 0),
(6, 'Almost never', 1),
(7, 'Sometimes', 2),
(8, 'Fairly Often', 3),
(9, 'Very Often', 4),
(10, 'Always', 4),
(11, 'True', 1),
(12, 'FALSE', 0),
(13, 'Yes', 1),
(14, 'No', 0)
GO
INSERT INTO [Test].[AnswerSet]
VALUES (1, 4),
(2, 5  ),
(3, 2  ),
(4, 3  ),
(5, 2  )
GO
INSERT INTO [Test].[AnswerSetContent]
VALUES (1, 1, 1),
(2, 1, 2),
(3, 1, 3),
(4, 1, 4),
(5, 2, 5),
(6, 2, 6),
(7, 2, 7),
(8, 2, 8),
(9, 2, 9),
(10, 3, 11),
(11, 3, 12),
(12, 4, 5),
(13, 4, 7),
(14, 4, 10),
(15, 5, 13),
(16, 5, 14)
GO
INSERT INTO [Solution].[Solution]
VALUES (1,
        'Sheep in Dream',
        'Game',
        'Sleep',
        'Mobile App',
        'Sheep in Dream is a game about getting a boy to sleep by making sheep jump over a log. The sheep are in the top left corner of the screen on a dream hill and the boy is in his bed at the bottom. '),
(2,
 'Love is in small things',
 'Game',
 'Relationship',
 ',Mobile App',
 'Love is…in small things is one of the romantic games made by Lunosoft. The game showcases the lively artwork of a South Korean artist who goes by the name Puuung and is a romantic title'),
(3,
 'My Oasis: Relaxing, Satisfying',
 'Game',
 'Communicate-Calm',
 'Mobile App',
 'My Oasis: Anxiety Relief Game is a relaxing game that helps in calming your mind, relieve your stress. This anti anxiety game helps in relaxation and calm sleeping.'),
(4,
 'Focus Plant: Pomodoro timer',
 'App' ,
 'Focus',
 'Mobile App',
 'Focus is a gamified focus study timer app to help people better manage their time and focus on the important things in their life. Some times self-discipline is just not enough to keep us away from the phones. This is when gamification comes in, the in-game achievements encourage users to stick with the app, better manage their time and get things done.'),
(5,
 'Wokamon - Walking app game',
 'Game',
 'Exercise',
 'Mobile App',
 'Wokamons are running out of resources and they need your help! Every step you take is turned into energy. Use it to feed, grow and collect Wokamons. The more you walk, the more Wokamons you can collect and the further you get to explore the magical Woka-worlds like candy desert, icy realm, mystical forest and more! Lend a helping hand and soon you will find, the more you help, the fitter you get!'),
(6,
 'Cats & Soup',
 'Game',
 'Relax',
 'Mobile App',
 'Looking for a cute cat game? Here is a peaceful animal forest where cats boil their delicious soup! An idle relaxing cat game perfect for cat moms and dads'),
(7,
 'Magic Fluids Lite',
 'Game',
 'Relax-Calm',
 'Mobile App',
 'Touch and simulate this magical fluid substance to get calm, trippy and creative! Gorgeous visual effects give a out of this world feel. Now with more presets and music!'),
(8,
 'Antistress - Relaxing games',
 'Game',
 'Relax-Calm',
 'Mobile App',
 'When you need relaxation, diversion or just a moment of distraction enjoy this collection of toys: hear the sound of a bamboo chime, play with wooden boxes, swipe gently your finger in the water, tap buttons, draw with chalks and so on!'),
(9,
 'Heaven Travel',
 'Game',
 'Relax',
 'Mobile App',
 'Lofn, a little girl who wakes up on an ethereal grassland, sets out on an adventure in order to save the Memory Tree. While she collects different memory pieces, she also discovers the surprising truth of her life. Other than unexpected plot twists, the story is presented in a unique way which we hope will stimulate the reader to look at life from a different perspective.'),
(10,
 'Worrydolls',
 'Game',
 'Relieve anxiety',
 'Mobile App',
 'Worrydolls gives you a small doll who is ready to listen to what is worrying you. Tell your worry to the doll, then track it over time. You can use Worrydolls like a journal to help you overcome anxiety and stress.'),
(11,
 'Happy Color',
 'Game',
 'Focus',
 'Mobile App',
 'Discover Happy Color®: a calming paint by numbers game. Relax by painting digital art, with exclusive nature, fashion, Disney, Marvel art templates and much more - whether you’re looking for a fun, creative moment or for anxiety relief, Happy Color® is the coloring app you need.'),
(12, 'Virtual bubble wrap', 'Game', 'Relax', 'Online', 'https://bubblespop.netlify.app'),
(13, 'Mandala Maker', 'Game', 'Creative', 'Online', 'https://mandalamaker.online'),
(14, 'Michael O''Mara Books', 'Game', 'Relax', 'Online', 'https://www.mombooks.com/mom/online-activities'),
(15,
 'Sym' ,
 'Game',
 'Survive',
 'Online',
 '"Sym is a puzzle-platformer that explores social anxiety disorder. Play as Josh, a teenage boy trying to reconcile a maze of two contrasting worlds that coexist within the blank spaces of each other - his perception of reality, and the world he created to avoid his fears. https://store.steampowered.com/app/342100/Sym/"'),
(16, '@longtrust', 'Video', 'Discovery', 'Tiktok', 'Khám phá phim theo từng thể loại trên nền tảng Netflix.'),
(17, '@gains2gains', 'Video', 'Motivation', 'Tiktok', 'Cung cấp các lời khuyên hữu ích vực dậy ý chí bản thân.'),
(18,
 '@mindful_tom',
 'Video',
 'Motivation',
 'Tiktok',
 'Clip tư vấn và cung cấp các tips tự thức tỉnh và chữa lành các căn bệnh tâm lý.'),
(19,
 '@bethanyylouisaa',
 'Video',
 'Healing',
 'Tiktok',
 'Các clip về phong cảnh đẹp, thơ mộng cùng nhạc nhẹ. Các clip tầm 15 giây.'),
(20, '@waterandlight', 'Video', 'Healing', 'Tiktok', 'Các clip về sóng biển đẹp. Các clip tầm 10 giây.'),
(21,
 '@chocoandpancake',
 'Video',
 'Healing',
 'Tiktok',
 'Các câu chuyện về cặp tình nhân là choco và pancake. Các clip ngắn thường mấy chục giây. (Tình cảm, thấu hiểu, dễ thương)'),
(22,
 '@dinosaurcouchcomics',
 'Video',
 'Healing',
 'Tiktok',
 'Có 2 loại clip khác nhau. Một là những câu chuyện của các chú khủng long với nhau. Hai là những câu chuyện của chú chó và cậu chủ. Các video clip tương đối ngắn tầm mấy chục giây. (nhân văn, dễ thương, ngớ ngẩn, thấu hiểu)'),
(23, '@lovely.words', 'Video', 'Healing', ',Tiktok', 'About lovely words in a lot of books'),
(24, '@the_simulator', 'Video', 'Discovery', 'Tiktok', 'Math'),
(25, '@planet_scape', 'Video', 'Discovery', 'Tiktok', 'Landscapes'),
(26,
 'Sky: Children of the Light',
 'Game',
 'Relationship',
 'Mobile App',
 'Experience the best of humanity in a place where you can meaningfully connect with others. In Sky, you can soar above the clouds, play instruments, or just relax and enjoy the beauty around you. There is no pressure. Just allow the experience to open up at your own pace. All are welcome, especially you!'),
(27, 'How to meditate', 'Meditation', 'Soft Exercise', 'Website', 'https://www.mindful.org/how-to-meditate/'),
(28,
 'Top 10 guided meditation',
 'Meditation',
 'Soft Exercise',
 'Website',
 'https://www.mindful.org/the-top-10-guided-meditations-of-2022/'),
(29,
 'List of meditation',
 'Meditation',
 'Soft Exercise',
 'Youtube',
 'https://www.youtube.com/watch?v=O-6f5wQXSu8&list=PLQiGxGHwiuD1kdxsWKFuhE0rITIXe-7yC'),
(30,
 'List of meditation 2',
 'Meditation',
 'Soft Exercise',
 'Youtube',
 'https://www.youtube.com/watch?v=HRuqe26F8SU&list=PLQiGxGHwiuD1OIV-vWbhZqy6iSkazC_Jd'),
(31,
 'Yoga''s tips',
 'Yoga',
 'Soft Exercise',
 'Website',
 'https://www.yogabasics.com/practice/yoga-for-beginners/yoga-tips-for-beginners/'),
(32, 'SarahBethYoga', 'Yoga', 'Soft Exercise', 'Youtube', 'https://www.youtube.com/@sarahbethyoga/videos'),
(33, 'YogaWithAdriene', 'Yoga', 'Soft Exercise', 'Youtube', 'https://www.youtube.com/@yogawithadriene/playlists'),
(34, 'Yograja', 'Yoga', 'Soft Exercise', 'Youtube', 'https://www.youtube.com/@Yograja/videos'),
(35, 'JessicaRichburg', 'Yoga', 'Soft Exercise', 'Youtube', 'https://www.youtube.com/@JessicaRichburg/videos'),
(36, 'The Skin Deep', 'Video', 'Understanding', 'Youtube', 'https://www.youtube.com/@TheSkinDeep'),
(37,
 '@happinessproject',
 'Picture',
 'Motivation',
 'Tiktok',
 'Các câu chuyện kể bằng các ảnh tầm 7, 8 ảnh về các thông điệp động viên, thấu hiểu, thông cảm, tips để chống lại sự trầm cảm.'),
(38, 'Rise: Energy & Sleep Tracker', 'App', 'Sleep', 'Mobile App', NULL),
(39, 'Loóna: calm, relax and sleep', 'App', 'Sleep', 'Mobile App', NULL),
(40, 'Calm', 'App', 'Exercise', 'Mobile App', NULL),
(41, 'Fabulous: Daily Habit Tracker', 'App', 'Motivation', 'Mobile App', NULL),
(42, 'Tangerine: Self-care & Goals', 'App', 'Motivation', 'Mobile App', NULL),
(43, 'Headspace: Mindful Meditation', 'App', 'Soft Exercise', 'Mobile App', NULL),
(44, 'Balance: Meditation & Sleep', 'App', 'Soft Exercise', 'Mobile App', NULL),
(45, 'BetterSleep: Relax and Sleep', 'App', 'Sleep', 'Mobile App', NULL),
(46, 'Endel: Focus, Sleep, Relax', 'App', 'Focus', 'Mobile App', NULL),
(47, 'Sanvello: Anxiety & Depression', 'App', 'Coaching', 'Mobile App', NULL),
(48, 'Moodi', 'Natural sound', 'Calm-relax', 'Website', 'https://www.moodil.com'),
(49, 'A Soft Murmur', 'Natural sound', 'Focus', 'Website', 'https://asoftmurmur.com'),
(50, 'My Noise', 'Sound', 'Relax-calm-focus', 'Website', 'https://mynoise.net'),
(51, 'Calm Sound', 'Natural sound', 'Sleep-relax', 'Website', 'https://www.calmsound.com'),
(52, 'WildAmbience', 'Natural sound', 'Relax', 'Website', 'https://wildambience.com'),
(53, 'Exhaler', 'Breathe', 'Calm', 'Website', 'https://xhalr.com'),
(54, 'Pixel Thoughts', 'Interact', 'Relieve Stress', 'Website', 'http://www.pixelthoughts.co/'),
(55, 'Connected Breath', 'Breathe', 'Calm', 'Website', 'http://www.connectedbreath.co'),
(56, 'Do Nothing', 'Nothing', 'Calm', 'Website', 'http://www.donothingfor2minutes.com'),
(57, 'Allolo', 'Natural sound', 'Relax', 'Website', 'http://www.allolo.ru/?id=14'),
(58,
 'RR: Eating Disorder Management',
 'App' ,
 'Avoid Eating Disorder',
 'Mobile App',
 'Recovery Record is the smart companion for managing your journey to recovery from eating disorders including anorexia nervosa, bulimia nervosa, binge eating disorder and ARFID. This app is also intended for people with general eating, weight and shape concerns.'),
(59,
 'Rosy - Women''s Sexual Health',
 'App' ,
 'Libido Issues',
 'Mobile App',
 'The Sexual Wellness Solutions We All Deserve. Developed by doctors and psychologists, Rosy is the first-of-its-kind platform for the 43% of us who experience sexual concerns. Our app meets women right where they are so they can take their sexual health into your own hands.')
GO
INSERT INTO [Solution].[CureOneByOne]
VALUES (1, 58, 1),
(2, 1, 2),
(3, 3, 3),
(4, 59, 4),
(5, 56, 5),
(6, 53, 6),
(7, 54, 7),
(8, 29, 8),
(9, 4, 9),
(10, 47, 10),
(11, 10, 11),
(12, 50, 12),
(13, NULL, 13),
(14, NULL, 14),
(15, 26, 15),
(16, 37, 16),
(17, 30, 17),
(18, NULL, 18),
(19, NULL, 19),
(20, NULL, 20),
(21, NULL, 21),
(22, NULL, 22),
(23, 2, 23),
(24, NULL, 24),
(25, 17, 25),
(26, NULL, 26),
(27, 15, 27),
(28, NULL, 28),
(29, NULL, 29),
(30, 17, 30),
(31, NULL, 31),
(32, 42, 32),
(33, NULL, 33),
(34, 55, 34),
(35, 12, 35),
(36, NULL, 36),
(37, NULL, 37),
(38, NULL, 1)
GO
INSERT INTO [Solution].[Recommendation]
VALUES (1, 30, 1),
(2, 18, 1),
(3, 13, 1),
(4, 53, 2),
(5, 11, 2),
(6, 49, 2),
(7, 42, 2),
(8, 1, 2),
(9, 11, 2),
(10, 47, 3),
(11, 43, 3),
(12, 26, 3),
(13, 38, 4),
(14, 8, 4),
(15, 6, 4),
(16, 7, 4),
(17, 30, 4),
(18, 27, 4),
(19, 21, 5),
(20, 23, 5),
(21, 10, 5),
(22, 34, 6),
(23, 13, 6),
(24, 52, 6),
(25, 1, 6),
(26, 45, 6),
(27, 22, 6),
(28, 51, 7),
(29, 43, 7),
(30, 3, 7),
(31, 14, 8),
(32, 25, 8),
(33, 9, 8),
(34, 39, 8),
(35, 47, 8),
(36, 25, 15),
(37, 38, 15),
(38, 16, 16),
(39, 32, 16),
(40, 45, 16),
(41, 15, 16),
(42, 42, 17),
(43, 58, 17),
(44, 16, 17),
(45, 56, 18),
(46, 32, 18),
(47, 10, 18),
(48, 48, 18),
(49, 24, 18),
(50, 19, 18),
(51, 18, 19),
(52, 11, 19),
(53, 21, 19),
(54, 55, 20),
(55, 25, 20),
(56, 16, 20),
(57, 54, 20),
(58, 20, 20)
GO

UPDATE [Test].[Result]
SET [Description] = ('Little Severe')
WHERE [Description] IS NULL
  AND Weight = 80;
GO
UPDATE [Test].[Result]
SET [Description] = ('Severe')
WHERE [Description] IS NULL
  AND Weight = 100;
GO